version: 2
jobs:
  setup_dependencies:
    docker:
      - image: circleci/python3.8.3
    steps:
      - checkout
      - restore_chache:
        key: deps-{{ checksum "requirements.lock" }}
      - run:
        command: |
          pip install --user -r requirements.lock
      - save_chache:
        key: deps-{{ checksum "requirements.lock" }}
        paths:
          - "~/.local"
test:
  docker:
    - image: circleci/python3.8.3
  steps:
    - checkout
    - restore_chache:
      key: deps-{{ checksum "requirements.lock" }}
    - run:
      command: |
        python -m unittest -v
workflows:
  version: 2
  all:
    jobs:
      - setup_dependencies
      - test:
        requires:
          - setup_dependencies
